### ISSUE TITLE
Should switch to us-west-2 before enabling GuardDuty

### ISSUE THREAD

**Issue by ahmgithubahm** [aws-samples/amazon-guardduty-hands-on#3]
I think the readme needs to ensure the tester has switched to the us-west-2 region before enabling GuardDuty, since that's where the CloudFormation stack is brought up.

**Comment by jmfuchs** [comment]
I went ahead and added a region indicator next to each console link to make it more clear for those not clicking on the links.  The console links should take you directly to the correct region.  Let me know if that makes it more clear.

**Comment by ahmgithubahm** [comment]
Hi Jesse.  Yes, that makes sense.  I was manually clicking my way to GuardDuty rather than following links from the readme - because obviously I knew better 😉 
thank you

**Comment by jmfuchs** [comment]
:smiley: Thanks for the feedback!  We'll be sure to incorporate that into other workshops as well.
